### ISSUE TITLE
Add highlight in feature title.

### ISSUE THREAD

**Issue by anteriovieira** [lodash/lodash.com#149]
Maybe it's just me, but I have a hard time navigating the documentation because the title of the feature is not in evidence.

A simple highlight can better separate resource blocks.

### Before:

<img src=https://cloud.githubusercontent.com/assets/1490347/26106360/13c24186-3a1c-11e7-8117-9c78a48bb677.png width=80%>

----

<img src=https://cloud.githubusercontent.com/assets/1490347/26106368/19feb750-3a1c-11e7-95f5-c1109439b89b.png width=80%>

----

### After:

<img src=https://cloud.githubusercontent.com/assets/1490347/26106381/23991f94-3a1c-11e7-9082-2c504eb42ef0.png width=80%>

----

<img src=https://cloud.githubusercontent.com/assets/1490347/26106385/272a45c0-3a1c-11e7-9586-1da46d985700.png width=80%>

----

<img src=https://cloud.githubusercontent.com/assets/1490347/26106661/ef2ef3f4-3a1c-11e7-8b8f-ea66847f6c70.png width=80%>

I also think it incorporates better the colors of the logo : )

**Comment by jdalton** [comment]
\cc @veksen for opinions.

**Comment by veksen** [comment]
It's definitely a step in the right direction, and it's one of the problem I am looking to fix, part of my proposed 2017 Lodash.com update.

However, I think only changing the color is avoiding the real problem here. The heading is hard to visualise because of the way the layout is.
* more generous margin is necessary between features
* a block layout could largely help 
* restructure of the information inside could make scanning easier 
* perhaps something like only showing clicked/searched features could help isolate information, and avoid visual noise while browsing

**Comment by jdalton** [comment]
Closing stale issue. Feel free to re-ping.
